### ISSUE TITLE
Cannot Login - Undefined Conversion Error

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/metasmoke#249]
This has been going on for the better part of a week or more.  Prevents making additional API keys for Smokey among other things.

May be related to Charcoal-SE/metasmoke#248 as well.

------

Specific error message: Encoding::UndefinedConversionError in CustomSessionsController#create

"\xC0" from ASCII-8BIT to UTF-8

Request parameters:
```
{"utf8"=>"✓",
 "authenticity_token"=>"r/HG0Fvc//39kaWoS2wdKmoToFLCt9cVrsPY2zSwjkk441lUr3sPnpWELXrF7rC7VzJpMB5cEgOhFtdjNEXwuw==",
 "user"=>{"email"=>"teward@ubuntu.com", "password"=>"[FILTERED]"},
 "commit"=>"Log in"}
```

```
activesupport (5.1.2) lib/active_support/core_ext/object/json.rb:36:in `encode'
activesupport (5.1.2) lib/active_support/core_ext/object/json.rb:36:in `to_json'
activesupport (5.1.2) lib/active_support/core_ext/object/json.rb:36:in `to_json'
activesupport (5.1.2) lib/active_support/json/encoding.rb:55:in `to_json'
json (2.1.0) lib/json/common.rb:224:in `generate'
json (2.1.0) lib/json/common.rb:224:in `generate'
activesupport (5.1.2) lib/active_support/json/encoding.rb:100:in `stringify'
activesupport (5.1.2) lib/active_support/json/encoding.rb:33:in `encode'
activesupport (5.1.2) lib/active_support/json/encoding.rb:20:in `encode'
actioncable (5.1.2) lib/action_cable/server/broadcasting.rb:45:in `block in broadcast'
activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
actioncable (5.1.2) lib/action_cable/server/broadcasting.rb:44:in `broadcast'
actioncable (5.1.2) lib/action_cable/server/broadcasting.rb:23:in `broadcast'
actioncable (5.1.2) lib/action_cable/channel/broadcasting.rb:13:in `broadcast_to'
app/models/concerns/websocket.rb:17:in `broadcast_event'
app/models/concerns/websocket.rb:25:in `broadcast_update'
activesupport (5.1.2) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.2) lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
activesupport (5.1.2) lib/active_support/callbacks.rb:511:in `block in invoke_after'
activesupport (5.1.2) lib/active_support/callbacks.rb:511:in `each'
activesupport (5.1.2) lib/active_support/callbacks.rb:511:in `invoke_after'
activesupport (5.1.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport (5.1.2) lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
activerecord (5.1.2) lib/active_record/callbacks.rb:344:in `_update_record'
activerecord (5.1.2) lib/active_record/timestamp.rb:107:in `_update_record'
activerecord (5.1.2) lib/active_record/persistence.rb:563:in `create_or_update'
activerecord (5.1.2) lib/active_record/callbacks.rb:336:in `block in create_or_update'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
activesupport (5.1.2) lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
activerecord (5.1.2) lib/active_record/callbacks.rb:336:in `create_or_update'
activerecord (5.1.2) lib/active_record/persistence.rb:129:in `save'
activerecord (5.1.2) lib/active_record/validations.rb:44:in `save'
activerecord (5.1.2) lib/active_record/attribute_methods/dirty.rb:35:in `save'
activerecord (5.1.2) lib/active_record/transactions.rb:308:in `block (2 levels) in save'
activerecord (5.1.2) lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/ubuntu/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
activerecord (5.1.2) lib/active_record/transactions.rb:210:in `transaction'
activerecord (5.1.2) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
activerecord (5.1.2) lib/active_record/transactions.rb:308:in `block in save'
activerecord (5.1.2) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
activerecord (5.1.2) lib/active_record/transactions.rb:307:in `save'
activerecord (5.1.2) lib/active_record/suppressor.rb:42:in `save'
devise (4.3.0) lib/devise/models/rememberable.rb:60:in `forget_me!'
devise (4.3.0) lib/devise/controllers/rememberable.rb:30:in `forget_me'
devise (4.3.0) lib/devise/hooks/forgetable.rb:7:in `block in <top (required)>'
warden (1.2.7) lib/warden/hooks.rb:15:in `block in _run_callbacks'
warden (1.2.7) lib/warden/hooks.rb:10:in `each'
warden (1.2.7) lib/warden/hooks.rb:10:in `_run_callbacks'
warden (1.2.7) lib/warden/manager.rb:52:in `_run_callbacks'
warden (1.2.7) lib/warden/proxy.rb:263:in `block in logout'
warden (1.2.7) lib/warden/proxy.rb:261:in `each'
warden (1.2.7) lib/warden/proxy.rb:261:in `logout'
devise (4.3.0) lib/devise/controllers/sign_in_out.rb:77:in `sign_out'
app/controllers/custom_sessions_controller.rb:17:in `block in create'
devise (4.3.0) app/controllers/devise/sessions_controller.rb:20:in `create'
app/controllers/custom_sessions_controller.rb:13:in `create'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:108:in `block in run_callbacks'
audited (4.5.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.1.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
audited (4.5.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.1.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
activesupport (5.1.2) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.10.5) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
rack-mini-profiler (0.10.5) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ArtOfCode-** [comment]
[status-fixed-by-unrelated-fix]
