### ISSUE TITLE
JS doesn't compile offline

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#556]
Super low priority, but I was trying to work on MS offline, and the JS doesn't compile, which seems strange. Not important, just if anyone has time and wants to poke at it.

**Comment by thesecretmaster** [comment]
I also ran it with the `--offline` flag, and even with that I get:

```
 10% building modules 2/2 modules 0 activeevents.js:183                            
      throw er; // Unhandled 'error' event
      ^

Error: addMembership ENODEV
    at Socket.addMembership (dgram.js:615:11)
    at Socket.<anonymous> ([parent]/metasmoke/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at startListening (dgram.js:156:10)
    at _handle.lookup (dgram.js:273:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
error Command failed with exit code 1.
```

**Comment by ArtOfCode-** [comment]
Update everything... I recall getting `Error: addMembership EINVAL` once upon a time for not having the right versions of things.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Updated yarn... not sure what else you want me to update. Still getting the error, only when I'm offline though. If I have internet, it works fine.
