### ISSUE TITLE
Pullapprove merge hook throws a redis traceback

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/metasmoke#588]
```
/var/railsapps/metasmoke/releases/20190211182219/app/controllers/application_controller.rb:105:in `block in log_redis'
/var/railsapps/metasmoke/releases/20190211182219/app/controllers/application_controller.rb:103:in `each'
/var/railsapps/metasmoke/releases/20190211182219/app/controllers/application_controller.rb:103:in `log_redis'
/var/railsapps/metasmoke/releases/20190211182219/app/controllers/application_controller.rb:77:in `block in redis_log_request'
/var/railsapps/metasmoke/shared/bundle/ruby/2.5.0/gems/rack-mini-profiler-1.0.1/lib/mini_profiler/profiling_methods.rb:39:in `step'
/var/railsapps/metasmoke/releases/20190211182219/app/controllers/application_controller.rb:70:in `redis_log_request'
```

**Comment by thesecretmaster** [comment]
What is the actual error?

**Comment by ArtOfCode-** [comment]
```
Redis::CommandError
ERR wrong number of arguments for HMSET
```

**Comment by thesecretmaster** [comment]
How can I repro this in dev?

**Comment by ArtOfCode-** [comment]
Don't know off the top of my head - probably send a POST to that route manually?

**Comment by thesecretmaster** [comment]
Didn't mean to close, not sure if fixed

**Comment by thesecretmaster** [comment]
Pretty sure this is fixed now -- githubcontroller stuff just isn't logged
