### ISSUE TITLE
/search (and MS main page) gets Redis OOM error 

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#592]
Just now, I got the following error from MS (at the time it was repeating anytime I tried the /search page):

### OOM command not allowed when used memory > 'maxmemory'.

> Extracted source (around line 29): 
> 
>     redis.zadd "requests/status/#{data[:status] || 'INC'}", request_timestamp, request_id

### Application Trace: 

    config/initializers/redis_logging.rb:29:in `block in <top (required)>'

### Full Trace:

```
redis (3.3.5) lib/redis/client.rb:121:in `call'
redis (3.3.5) lib/redis.rb:1534:in `block in zadd'
redis (3.3.5) lib/redis.rb:58:in `block in synchronize'
/home/ubuntu/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
redis (3.3.5) lib/redis.rb:58:in `synchronize'
redis (3.3.5) lib/redis.rb:1528:in `zadd'
config/initializers/redis_logging.rb:29:in `block in <top (required)>'
activesupport (5.2.2) lib/active_support/notifications/fanout.rb:129:in `finish'
activesupport (5.2.2) lib/active_support/notifications/fanout.rb:48:in `block in finish'
activesupport (5.2.2) lib/active_support/notifications/fanout.rb:48:in `each'
activesupport (5.2.2) lib/active_support/notifications/fanout.rb:48:in `finish'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:29:in `ensure in instrument'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:29:in `instrument'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2) lib/action_view/rendering.rb:32:in `process'
rack-mini-profiler (1.0.1) lib/mini_profiler/profiling_methods.rb:78:in `block in profile_method'
actionpack (5.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
rack-mini-profiler (1.0.1) lib/mini_profiler/profiler.rb:171:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

I'm also getting a similar response from the MS main page:

### OOM command not allowed when used memory > 'maxmemory'.

> Extracted source (around line #29): 
> 
>     redis.zadd "requests/status/#{data[:status] || 'INC'}", request_timestamp, request_id

Same Application Trace.

**Comment by thesecretmaster** [comment]
Fixed in https://github.com/Charcoal-SE/metasmoke/commit/e01eb9434883fb4dd99af98cc51dcc01158461aa
