### ISSUE TITLE
Traceback when adding a new domain; target of repeat operator is not specified: /*.wikipedia.org/

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#858]
https://metasmoke.erwaysoftware.com/domains/new crashed for me when attempting to add xiaomitrends.com

Not sure I'm able to copy/paste the diagnostics correctly, but here goes.

RegexpError in SpamDomainsController#create
target of repeat operator is not specified: /*.wikipedia.org/
Extracted source (around line #41):

    39    after_create do
    40      groups = Rails.cache.fetch 'domain_groups' do
    41          DomainGroup.all.map { \|dg\| !dg.regex ? nil : [Regexp.new(dg.regex), dg.id] }.compact.to_h
    42       end
    43      groups.keys.each do \|r\|
    44        DomainGroup.find(groups[r]).spam_domains << self if r.match? domain

Rails.root: /var/railsapps/metasmoke/releases/20210426205533
```
Application Trace | Framework Trace | Full Trace
app/models/spam_domain.rb:41:in `initialize'
app/models/spam_domain.rb:41:in `new'
app/models/spam_domain.rb:41:in `block (3 levels) in <class:SpamDomain>'
activerecord (5.2.4.4) lib/active_record/relation/delegation.rb:71:in `each'
activerecord (5.2.4.4) lib/active_record/relation/delegation.rb:71:in `each'
app/models/spam_domain.rb:41:in `map'
app/models/spam_domain.rb:41:in `block (2 levels) in <class:SpamDomain>'
activesupport (5.2.4.4) lib/active_support/cache.rb:323:in `block in fetch'
activesupport (5.2.4.4) lib/active_support/cache.rb:694:in `block in save_block_result_to_cache'
activesupport (5.2.4.4) lib/active_support/cache.rb:663:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
activesupport (5.2.4.4) lib/active_support/cache.rb:663:in `instrument'
activesupport (5.2.4.4) lib/active_support/cache.rb:693:in `save_block_result_to_cache'
activesupport (5.2.4.4) lib/active_support/cache.rb:323:in `fetch'
app/models/spam_domain.rb:40:in `block in <class:SpamDomain>'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:426:in `instance_exec'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:517:in `each'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:133:in `run_callbacks'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
activerecord (5.2.4.4) lib/active_record/callbacks.rb:346:in `_create_record'
activerecord (5.2.4.4) lib/active_record/timestamp.rb:102:in `_create_record'
activerecord (5.2.4.4) lib/active_record/persistence.rb:705:in `create_or_update'
activerecord (5.2.4.4) lib/active_record/callbacks.rb:342:in `block in create_or_update'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
activerecord (5.2.4.4) lib/active_record/callbacks.rb:342:in `create_or_update'
activerecord (5.2.4.4) lib/active_record/persistence.rb:275:in `save'
activerecord (5.2.4.4) lib/active_record/validations.rb:46:in `save'
activerecord (5.2.4.4) lib/active_record/transactions.rb:310:in `block (2 levels) in save'
activerecord (5.2.4.4) lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
activerecord (5.2.4.4) lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
activerecord (5.2.4.4) lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/undo/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
activerecord (5.2.4.4) lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
activerecord (5.2.4.4) lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
activerecord (5.2.4.4) lib/active_record/transactions.rb:212:in `transaction'
activerecord (5.2.4.4) lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
activerecord (5.2.4.4) lib/active_record/transactions.rb:310:in `block in save'
activerecord (5.2.4.4) lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
activerecord (5.2.4.4) lib/active_record/transactions.rb:309:in `save'
activerecord (5.2.4.4) lib/active_record/suppressor.rb:44:in `save'
app/controllers/spam_domains_controller.rb:51:in `create'
actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
audited (4.9.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
audited (4.9.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.4) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.4) lib/action_view/rendering.rb:32:in `process'
rack-mini-profiler (1.1.6) lib/mini_profiler/profiling_methods.rb:78:in `block in profile_method'
actionpack (5.2.4.4) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.4) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
rack-mini-profiler (1.1.6) lib/mini_profiler/profiler.rb:184:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```
Request
Parameters:
```
{"utf8"=>"✓", "authenticity_token"=>"lotsofbase64==", "spam_domain"=>{"domain"=>"xiaomitrends.com"}}
```

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/data/sql/queries/269-domain-groups-search?search=wikipedia reveals two domain groups matching "wikipedia", the first of which is botched (item 24).

**Comment by tripleee** [comment]
@Undo1  as a workaround, can you remove the problematic entry?

**Comment by user12986714** [comment]
Obviously, this is due to the invalid regex `*.wikipedia.org`. Maybe we can add some validation when adding a new domain group.

**Comment by tripleee** [comment]
Regression: Can't create domains at all again.

```
target of repeat operator is not specified: /*.wikipedia.org/

Extracted source (around line #41):

39   after_create do
40     groups = Rails.cache.fetch 'domain_groups' do
41       DomainGroup.all.map { \|dg\| !dg.regex ? nil : [Regexp.new(dg.regex), dg.id] }.compact.to_h <============
42     end
43     groups.keys.each do \|r\|
44       DomainGroup.find(groups[r]).spam_domains << self if r.match? domain
```

**Comment by tripleee** [comment]
If you want a test case, the one I wanted to add was gamesncomps.com to link back to https://metasmoke.erwaysoftware.com/post/324790

**Comment by tripleee** [comment]
(I guess the code is fine, but the incorrect regex needs to be removed before it can work.)

**Comment by tripleee** [comment]
Oh NVM, I found the botched testing group #27 and removed it.

id | name | regex | created_at | updated_at
-- | -- | -- | -- | --
27 | Testing Group | *.wikipedia.org | 2021-09-09 15:13:54 UTC | 2021-09-09 15:13:54 UTC

Good thing I had enough details in my testing notes before.
